spring:
  # jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '#Root123'
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5

logging:
  level:
    root: warn
    gy.finolo.springbootmybatisplus.dao: trace
#  pattern:
#    console:

