spring:
  profiles:
    active: dev

  # 文本消息国际化
  messages:
    basename: i18n/messages

  jackson:
    default-property-inclusion: non_null

config:
  fixDelay: 1000

logging:
  level:
    root: info
    gy.finolo.springbootmybatisplus.dao: trace
#  pattern:
#    console:

# ----------- actuator -----------
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, info

info:
  app-name: springboot-mybatis-plus
  author: simon
