spring:
  # jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-mybatis-plus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5

  # redis
  redis:
    host: 192.168.229.130
    # port: 6379
    timeout: 300

  # rabbitmq 基本配置
  rabbitmq:
    addresses: 172.16.64.240
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000

    # rabbitmq consumer 配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        # 需要代码ack
        acknowledge-mode: manual
        prefetch: 1

    # producer 配置
    publisher-confirm-type: correlated

  # 文本消息国际化
  messages:
    basename: i18n/messages

  jackson:
    default-property-inclusion: non_null

elasticsearch:
  hosts: localhost:9200

config:
  fixDelay: 1000

logging:
  level:
    root: info
    gy.finolo.springbootmybatisplus.dao: trace
#  pattern:
#    console:

# ----------- actuator -----------
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, info